### ISSUE TITLE
ListView Command / Parameters

### ISSUE THREAD

**Issue by ianvink** [MichaelRumpler/GestureSample#12]
XF 3.5

In a ListView, how do I set a Command and CommandParameter so that I get the item tapped?

I tried  :

                            TappedCommand="{Binding ItemTappedCommand}"
                            TappedCommandParameter="{Binding .}"

But I get the ViewModel as the item passed tot he Command handler. I want the tapped bound item.

**Comment by MichaelRumpler** [comment]
If you add commands to the ListView, then you get notified by the ListView and it tells you, which ListView was tapped.
You want to use the handlers on the Cells.
Look at the GestureSample. There are many samples there which show exactly what you need.

**Comment by ianvink** [comment]
On the list view xaml all the examples use events to determine which model item was selected. We use custom cells shared around so we wanted the command to be on the list view 

(We are customers)

**Comment by MichaelRumpler** [comment]
As I already said if you put the command on the ListView, you only get the information, which ListView has been tapped. That is not what you want. The ListView.SelectedItem will probably only be updated after the tap events.
I usually use a Command without CommandParameter because then the MR.Gestures.*EventArgs will be passed to the handler and those EventArgs give you much more information about the touch event than a simple view model.
