### ISSUE TITLE
[UWP] LongPressing in hidden element

### ISSUE THREAD

**Issue by MarMarIV** [MichaelRumpler/GestureSample#17]
Hi,
  when i use LongPressingCommand on Button and button is hidden (Visible=False), then area, where is hidden button still reacts on long press

NuGet version: 2.1.0 (1.5.3 same problem)

**Comment by MichaelRumpler** [comment]
I could not reproduce this with a `Button` where `IsVisible=false`, but I could set the container invisible and reproduce the bug like that.

This will be fixed in the next version. If you have a small repro project where it happens for a hidden `Button`, then please send it to me and I'll have a look.

**Comment by MichaelRumpler** [comment]
Version 2.1.1 is now available on NuGet.
