### ISSUE TITLE
MR Gestures Not Working with Xcode 11.4

### ISSUE THREAD

**Issue by dbagno** [MichaelRumpler/GestureSample#26]
Updated to the latest version of Xcode and Xamarin.  My MRGestures specific screens no longer work.  Tried running the MRGestures sample project and it had the same problem.  Views that use to work like the webView no longer work.

**Comment by dbagno** [comment]
I tried using the updated version of  MR.Gestures 2.1.2  with Xcode 11.3.   It did not work.  FYI- I down graded the most recent version of visual studio from April 1st to the previous version to MR.Gestures 2.1.1 work again on IOS

**Comment by MichaelRumpler** [comment]
Usually Xcode does not prevent any packages from working. Most of the time, the problem is in Xamarin.iOS.
Currently there is [a bug in Xamarin.iOS](https://github.com/xamarin/Xamarin.Forms/issues/10162) which prevents all gesture recognizers from working on iOS 13.4. I implemented a workaround in MR.Gestures 2.1.2.
I also updated the GestureSample today to Xamarin.Forms 4.5 and MR.Gestures 2.1.2 and that works on iOS 13.4. I don't know which versions you have currently, but give the GestureSample a try.

**Comment by dbagno** [comment]
Thanks for the quick turnaround.  That was fast

**Comment by pupauoga** [comment]
Hi
When I upgrade to 2.1.2 and run on Microsoft-hosted agent with the latest [software upgrades](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) I get this error:

 **`MTOUCH : error MT2002: Failed to resolve "UIKit.UIGesturesEvent" reference from "Xamarin.iOS...."`**
> Usually Xcode does not prevent any packages from working. Most of the time, the problem is in Xamarin.iOS.
> Currently there is [a bug in Xamarin.iOS](https://github.com/xamarin/Xamarin.Forms/issues/10162) which prevents all gesture recognizers from working on iOS 13.4. I implemented a workaround in MR.Gestures 2.1.2.
> I also updated the GestureSample today to Xamarin.Forms 4.5 and MR.Gestures 2.1.2 and that works on iOS 13.4. I don't know which versions you have currently, but give the GestureSample a try.

**Comment by MichaelRumpler** [comment]
I quote a message where I said that "Most of the time, the problem is in Xamarin.iOS."
Your error message contains "Failed to resolve "UIKit.UIGesturesEvent" reference from "Xamarin.iOS".

Why do you think that this is caused by MR.Gestures? Raise the bug with Microsoft.
