### ISSUE TITLE
iOS : ScrollView is blocked after few swipes

### ISSUE THREAD

**Issue by MathieuJack** [MichaelRumpler/GestureSample#28]
[TestMrScrollview.zip](https://github.com/MichaelRumpler/GestureSample/files/4741578/TestMrScrollview.zip)

Repro Step : 
1- compile & launch the attached sample app, on a physical iPhone
2- swipe to the left (even if the scroll view is already on its left)
3- Then try to swipe to the right or anywhere

Expected : 
The swipes in 3 work, and scrollView is scrolled

Result : 
The swipes in 3 have no result. ScrollView is "blocked".

Note  1 : problem does not occur on simulator
Note 2 : problem does not occur if I use the "standard" (no-MR) scrollView
Note 3 : problme does not occur if I don't subscribe to event "up"
Note 4 : Looks like this problem occurs only if this view has a navigation bar (with "Back"). If I don't use a NavigationPage and another page inserted before, there is no problem.
Note 4 : Problem is reproduced using a iPhone 7, with iOS 13.3

**Comment by MichaelRumpler** [comment]
Sorry for the late reply.

I can't reproduce the problem on my iPad and I don't have an iPhone anymore.

Maybe you can use `Panning`/`Panned` instead of `Scrolled`. `Panning` comes while you move your finder on the `ScrollView` and `Panned` is raised only after you lifted your finger - so roughly at the same time as `Up`.
But these events are not completely equivalent. `Scrolled` is still raised a few times when the `ScrollViewer` bounces after the finger is lifted.

You also may try `Panned` (instead of `Up`) and `Scrolled`.

**Comment by MathieuJack** [comment]
Panned and Scrolled did not work. I tried all events.
Without answer after few days, I finally wrote my own CustomRenderer.

**Comment by MichaelRumpler** [comment]
Multiple gesture handlers will always interact. I seem to do something in the UpDownGestureRecognizer which Apple doesn't like, but I followed all the docs I know. So there's nothing I can do about it.
