### ISSUE TITLE
Gesture Event Handlers are Released Upon Returning from a Popped Content Page - MAUI 8 RC1

### ISSUE THREAD

**Issue by appsure** [MichaelRumpler/GestureSample#45]
I'm running into an issue moving to the latest MAUI .net 8 Release Candidate.  I've been using all of the previews so far (I know, how adventurous of me) and things have been solid on the MR. Gestures front until now.  Seems when pushing a ContentPage then Popping back, any of your controls' Up/Down/etc event handlers are getting GC'd/released and no longer work.  They've done a lot of Memory Leak work lately and may have been too aggressive releasing event handlers.  I've only concentrated on iOS so far, haven't tried Android.

I've noticed if I use a stock MAUI button to invoke the initial ContentPage push, upon popping, the stock button's Clicked event handler is preserved.  So there must be some filtering/branching based on the base control type, I would assume.  

I also discovered that your Clicked event is preserved, but not the others which I was using (Up/Down/etc).  Perhaps since it uses a basic EventHandler delegate instead of your specific EventHander<xyz> delegates used on the other events, this could be a clue.  Repo below:

https://github.com/appsure/MrGesturesMaui8RC1.git

**Comment by appsure** [comment]
Dove a bit deeper.  Looks as if ViewElements have their UnLoaded event fired upon Pushing the new ContentPage.  Perhaps you're releasing/disposing your platform gesture recognizers there?  This behavior may be new with this RC1.

**Comment by MichaelRumpler** [comment]
Always the same with MAUI/Xamarin.Forms. After an update it takes me a full day to get it to compile - then 30mins to find the problem.

Unfortunately the fix is not as easy. As you correctly noticed, the `Unloaded` event is now raised when a new page is pushed. This was not the case before so I could use that event to dispose my gesture handlers.

I don't know if that is a bug in MAUI or if the life cycle management changed. Last year @PureWeen [said we should use Unloaded](https://github.com/dotnet/maui/issues/3604#issuecomment-1102845725). The mentioned docs [have never been written](https://github.com/dotnet/maui/issues/7381). So I simply don't know how I should handle this. And this is my last day in the office before two weeks of vacation. So unfortunately I'm running out of time here.

**Comment by appsure** [comment]
Feel your pain there, thanks for the links/info.  Ok, so we're then probably talking about your own resource management (ref counting etc).  How about detecting when a Page is destroyed (removed from the Window) and use that to release your resources?  What is MAUI doing to release the Clicked event handler for the Stock Button?  Could you release a version in the meanwhile as a beta that doesn't explicitly release during the Unloaded event and just let the .Net GC take care of it eventually?  Anyhow, enjoy your vacation!

**Comment by MichaelRumpler** [comment]
There is also an [issue in MAUI](https://github.com/dotnet/maui/issues/16697) about this. I'll try to find a workaround, but as they didn't document how / when we could handle cleanup, I'm not sure if I'll find anything. You may upvote the MAUI issue.

**Comment by MichaelRumpler** [comment]
Seems like I can use the `HandlerChanging` event instead. See https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/#handler-lifecycle.
I still need to test this on different MAUI versions, but it looks good at least in .NET8 RC1.

**Comment by MichaelRumpler** [comment]
I released version 4.0.0 now. This version uses `HandlerChanging` instead of `Unloaded`. It works at least in .NET8 rc1 and rc2.

**Comment by appsure** [comment]
Thanks, I'll try this out.
